awk: (FILENAME=tf.nfkb.bed FNR=248) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.gtf FNR=363) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.gtf FNR=342) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.nfkb.gtf FNR=384) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.nfkb.fasta FNR=1050) fatal: print to "standard output" failed (Broken pipe)
